fixtures:
  repositories:
    concat: "git://github.com/ripienaar/puppet-concat.git"
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    wordpress: "#{source_dir}"
