fixtures:
  repositories:
    concat:
      repo: 'git://github.com/ripienaar/puppet-concat.git'
      ref: '1.0.0'
    mysql:
      repo: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref: '2.1.0'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
  symlinks:
    wordpress: "#{source_dir}"
