---
# Broken bundler on travis CI - https://github.com/bundler/bundler/issues/2784
before_install:
  - gem update --system 2.1.11
  - gem --version
language: ruby
bundler_args: '--without development'
before_script: "gem install --no-ri --no-rdoc bundler"
script: 'bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'
after_success:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - .forge-releng/publish
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION=2.7.23
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.2
matrix:
  allow_failures:
  - env: PUPPET_VERSION=2.7.23
  - env: PUPPET_VERSION=3.4.2
  - rvm: 1.8.7

  global:
  - PUBLISHER_LOGIN=hunner
  - secure: |-
      Xv3W1UnVsdjpKRv8wOabAszW8AAzaFXTCpo/aEl1XZBAHG8pM3bxnkWV8vH0
      Sq/7joOco22ztqyhuUyVNYmui50gfhCvepgfK6ZMmgTK5pC1rhgNEVHzfWGo
      NfYxz4KRYBJD7yKsK7Jtuicbd/D9f6jQ5XpkNWICavref57DgNk=
notifications:
  email: false
